name: Build and Push Docker Image

on:
    push:

jobs:
    build_and_push:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v3
                with:
                    context:
                    push: true
                    tags: ghcr.io/essioui/github_actions:latest
